name: check-and-deploy
on:
  - push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: deno lint
      - run: deno fmt --check
      - run: deno cache src/main.ts
  deploy:
    if: github.ref == 'refs/heads/master'
    name: deploy
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          cd ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ./id_rsa
          sudo chmod 600 ./id_rsa
        shell: bash
      - name: deploy
        run: >
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -o StrictHostKeyChecking=no
          "cd detachhead
          && git fetch
          && git checkout -B master origin/master
          && (docker stop detachhead || true)
          && (docker rm detachhead || true)
          && docker build -t detachhead .
          && docker run -d --name detachhead -p 8000:8000 detachhead"
